### ISSUE TITLE
[Feature] 领先一步：提前适配 MAH 的新 API

### ISSUE THREAD

**Issue by BlueGlassBlock** [GraiaProject/Ariadne#102]
**使用场景**
用到新 API 的时候

**你想要的解决方案**
加上就对了

**其他**
[project-mirai/mirai-api-http](https://github.com/project-mirai/mirai-api-http/tree/dev)

**Comment by BlueGlassBlock** [comment]
新的事件类型：`FriendSyncMessage` `GroupSyncMessage` `TempSyncMessage` `StrangerSyncMessage`
新的元素类型：`MarketFace`
新的 API: `getUserProfile` [MAH#539](https://github.com/project-mirai/mirai-api-http/pull/539))

**Comment by GreyElaina** [comment]
简单写一写就得了

**Comment by BlueGlassBlock** [comment]
`0.5.3` 已完成
