### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by SinCerely023** [GraiaProject/Ariadne#122]
**问题**
Ariadne更新0.6.8后，接收事件时抛出 RuntimeWarning: coroutine 'Queue.put' was never awaited, 导致事件无法正确处理, 各事件均存在该问题. Ariadne回退至0.6.7无该问题.

**如何复现**
使用官方文档中最简单的demo, 在收到FriendMessage事件是就能报出该RuntimeWarning, 且不会有相应回复.

**使用环境:**

- 系统: win11 21H2
- MAH 版本: 2.3.3
- Ariadne 版本: 0.6.8
- Python 版本: 3.8.8
- 其他 Graia 库版本: Broadcast 0.16.1
- 其他 有关 库版本: asyncio 3.4.3

**日志**
控制台输出:
...\site-packages\graia\ariadne\adapter\forward.py:242: RuntimeWarning: coroutine 'Queue.put' was never awaited
  self.event_queue.put(self.build_event(data))
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

**Comment by GreyElaina** [comment]
了解了.
