### ISSUE TITLE
[Version Proposal] 0.7.0

### ISSUE THREAD

**Issue by BlueGlassBlock** [GraiaProject/Ariadne#124]
0.7.0 将会替换现在的后端处理，改用 Graia Amnesia 提供的，从 Avilla 来的一些通用部件。

这将会是一个 **不兼容更新**，所以相应的我们会提供一个迁移指南。

- [x] #165 
- [x] #156 
- [x] #167 
- [x] #166

**Comment by GreyElaina** [comment]
不需要 Breaking 吧, 你可以继承啊...

不过 Breaking 一下也无所谓.

**Comment by GreyElaina** [comment]
我帮你列一下需要做的事情:

 - 切换到由 Amnesia 提供的 MessageChain, 允许继承.
   - 因为 Amnesia 没有使用 `pydantic`, 所以你需要把 build chain 方法放在外面.
   - 比如你要用的那些 as mapping string 等方法, 你也可以放在一个 utilles 模块里面.
 - `PlainText = graia.amnesia.elements.Text`, 当然, 你需要继承一下.
 - `as display` 我扬掉了, 换成 `__str__` 了, 你想的话可以直接加回去.
 - 要给每个账号一个 `event` 和 `action`/`send`/`command` 的 Adapter(类似 avilla.onebot 的 `OnebotConnection`, 允许两个都指向同一个)
   - 这个是为了把你那个奇怪的 `CombineAdapter` 换成比较好看的...好吧你不想做我也没办法.
 - 让 Ariadne 获取一个 LaunchManager, 无论是让她自己当(继承), 还是直接实例化我都无所谓, 不过这里建议后者.
 - 写一个 `ElizabethService`, 用 Service API:
   - 一个 `ElizabethAccountInterface`(暂定), 用于底层操作 mah 的 api, 类似 avilla.onebot 那个用 `get_interface` 获取的.
   - 把所有账号的事件获取放在 Service 启动组件的 mainline 里面, 记得 try 住, 类似你那个 daemon 一样, 不过是对于多账户的.
   - 啊, 对, 我打算让 Ariadne 原生支持一下多账号 -> 毕竟 LaunchManager 只能同一时刻 `launch_blocking` 一个.
 - 剩下的我再想想吧, 记得让 @RF-Tar-Railt 也用上 Amnesia, 不过他说他会记得, 我觉得没问题.

**Comment by GreyElaina** [comment]
补充:

 - Service 的 Status, 每个 get_status 都是对你 Service 实例里面那个对应的 Status 实例取帧(frame 方法), 我觉得这个交互可以改成更友好的方式, 不过现在先这样.
 - 上面一点的前置: 你对一个 account 有 status 的报告和维护, 用个 `Dict[int, Status]` 就差不多了.

**Comment by GreyElaina** [comment]
- Service 要记得检查, 因为 `LaunchManager` 类似单例, 所以注入 `ElizabethService` 时记得先判断一下, 没有再实例化加进去

**Comment by GreyElaina** [comment]
我可能会把新的 `Transport` 或者说整个 `avilla.io` 下放到 amnesia.
原因：我看你connection写的异常痛苦
