### ISSUE TITLE
[Docs] 迁移文档

### ISSUE THREAD

**Issue by BlueGlassBlock** [GraiaProject/Ariadne#125]
- [x] 迁移所有文档到 [`Document`](https://github.com/GraiaProject/Document) , 仅在此处保留 API ref
- [x] 使用 Releases 来管理 changelog

**Comment by BlueGlassBlock** [comment]
![image](https://user-images.githubusercontent.com/50769752/171407940-a817e7e3-da09-4937-8a51-4a38c9662d17.png)

**Comment by SAGIRI-kawaii** [comment]
![image](https://user-images.githubusercontent.com/45849471/171409621-7979dd7d-52e1-4e6d-88ec-9de46a9515d4.png)

**Comment by SAGIRI-kawaii** [comment]
![image](https://user-images.githubusercontent.com/45849471/171410200-143e7835-402c-4502-977c-9ee30fad5470.png)
https://graia--156.org.readthedocs.build/projects/dev/advance/commander/#arg

**Comment by SAGIRI-kawaii** [comment]
![image](https://user-images.githubusercontent.com/45849471/171412061-ad32e689-8200-4a0e-bffd-37a31892f223.png)
https://graia--156.org.readthedocs.build/projects/dev/migrate/guide/#_4
