### ISSUE TITLE
[Feature] 连接 MAH 失败达到一定次数时自动退出

### ISSUE THREAD

**Issue by Redlnn** [GraiaProject/Ariadne#16]
**使用场景.**
无人值守且 MAH 挂了，同时 loguru 会记录 log 到日志文件时，可以防止 log 文件无限增大

**你想要的解决方案**
连接 MAH 失败或者 Adapter 异常停止达到一定次数时自动退出

**是否已有相关实现**
母鸡

**其他内容**
最好能允许在初始化 Ariadne 时传入参数改变自动退出的阈值

**Comment by BlueGlassBlock** [comment]
Will be added in `0.4.0`.
