### ISSUE TITLE
[Bug] 当消息链中的 App 元素用 asPersistentString() 转换得到字符串再用 fromPersistentString() 转换回来会报错

### ISSUE THREAD

**Issue by Redlnn** [GraiaProject/Ariadne#17]
**问题**
B站分享的App消息用 `asPersistentString()` 转换得到字符串，再用 `fromPersistentString()` 转换为消息链时会报错

**如何复现**
使用 `fromPersistentString()` 将[这个字符串（pastebin 有效期一周）](https://pastebin.com/ButaWi9s)转换为消息链会报 `json.decoder.JSONDecodeError` 错误

**预期行为**
不报错~

**使用环境:**
 - 系统: Windows 11
 - MAH 版本: 2.3.3
 - Ariadne 版本: 0.4.0-a9
 - Python 版本: 3.10
 - 其他 Graia 库版本: bcc 0.13.2
 - 其他 有关 库版本:

**日志/截图**
![}~7$~AW86N`R}67_M97ZONW](https://user-images.githubusercontent.com/41742767/141473411-424a5f94-8804-4ab5-af6b-21d1e2ff3502.jpg)

**Comment by BlueGlassBlock** [comment]
是 regex 的 问题
已在 e9b0c41250c09299486c00dcc1e7ba9d4ff3356b (0.4.0-a10) 修复
