### ISSUE TITLE
[Feature]提供预设Interrupt

### ISSUE THREAD

**Issue by I-love-study** [GraiaProject/Ariadne#18]
**使用场景.**
在需要较为简单的中断的时候

**你想要的解决方案**
跟V4一样的中断预设

**是否已有相关实现**
https://github.com/GraiaProject/Application/blob/master/src/graia/application/interrupts.py

**其他内容**
你认为重要的其他内容。

**Comment by GreyElaina** [comment]
v4 中的是给之前用户用的, 也就是给 Interrupt v1 用的, 在现代的 Waiter API 下, 再用那些就很不好看了

**Comment by I-love-study** [comment]
但是每次创建一个简单的中断都需要重新创建一个waiter是不是有点麻烦呢

**Comment by BlueGlassBlock** [comment]
@I-love-study
you can reuse your personal waiter function definitions somehow ...
I'll write a guide later. (Maybe next week)
