### ISSUE TITLE
ImportError: cannot import name 'adapter_ctx' from 'graia.ariadne.context' 

### ISSUE THREAD

**Issue by bakaEC** [GraiaProject/Ariadne#189]
**问题**

小弟不才，移植了个人写的项目之后发现adapter_ctx的Import error，重装MCL和graia-ariadne都试过了，还是如此。

**使用环境:**

- 系统:
- Ariadne 版本:graia_ariadne-0.7.18-py3-none-any.whl
- Python 版本:3.105

**日志**
PS C:\Users\Administrator\Desktop\bot\> python .\main.py
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\bot\main.py", line 8, in <module>
    from graia.ariadne.context import adapter_ctx
ImportError: cannot import name 'adapter_ctx' from 'graia.ariadne.context' (C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\graia\ariadne\context.py)

**Comment by BlueGlassBlock** [comment]
0.7 没有 `adapter_ctx` 了，可以说一下你的用途

**Comment by bakaEC** [comment]
问题已解决，之前用于获取session，现在跟着文档已经OK了😆
