### ISSUE TITLE
[Feature] 负载均衡

### ISSUE THREAD

**Issue by BlueGlassBlock** [GraiaProject/Ariadne#19]
**使用场景.**
通过同时操纵多个QQ减缓风控

**你想要的解决方案**
使用 `MultiAdapter` 类实现

**是否已有相关实现**
[Hex-Dragon/bot_luo_core](https://github.com/Hex-Dragon/bot_luo_core/)

**其他内容**
无

**Comment by GreyElaina** [comment]
我觉得你写个 Gateway 就好了, 该网关干的事情让网关干, 别让框架处理,  到时候扩展规模上不去还不方便迁移.

**Comment by BlueGlassBlock** [comment]
先扔到这里

后面可以再转
