### ISSUE TITLE
[Feature] 获取群历史消息

### ISSUE THREAD

**Issue by RaphaelCS** [GraiaProject/Ariadne#241]
**使用场景**

在需要查询群历史消息时，可以主动获取群历史消息

**你想要的解决方案**

在Ariadne类中添加类似`get_roaming_message`的API，目前这个API貌似只支持好友的历史消息，不支持群历史消息

**是否已有相关实现**

未见

**其他内容**

无

**Comment by GreyElaina** [comment]
mirai-api-http 尚未支持相关 API.
