### ISSUE TITLE
[Feature] 与FastApi不能很好的配合

### ISSUE THREAD

**Issue by doveppp** [GraiaProject/Ariadne#243]
**使用场景**
使用Fastapi和Aradne搭建api的时候

**你想要的解决方案**

二者的启动方式都是阻塞的，不能同时启动。另外我试过将Ariadne放在线程里启动，会因为loop不一致问题报错。

**是否已有相关实现**
目前的解决方式是使用aiohttp搭建web服务
```python
  import asyncio
  qq_bot._patch_launch_manager()
  tasks = [_run_app(app, host="0.0.0.0", port=8000), qq_bot.launch_manager.launch()]
  qq_bot.service.loop.run_until_complete(asyncio.wait(tasks))
```
其中_run_app是启动aiohttp web服务的
**其他内容**

**Comment by GreyElaina** [comment]
你是否清醒.jpg

试试 graiax-fastapi

**Comment by doveppp** [comment]
![72cab3af724e45f2fc637a1f8f90ea4d](https://github.com/GraiaProject/Ariadne/assets/54977106/d6e9f8ac-3f97-4849-bdc6-190eae4aa503)
