### ISSUE TITLE
该项目是否还在维护？

### ISSUE THREAD

**Issue by Yang-qwq** [GraiaProject/Ariadne#256]
您好，

首先感谢您为这个项目所做的工作。我注意到最近该项目从约1年前就没有了任何提交，因此我想确认一下该项目是否还在维护中。

非常感谢您的时间和回复。

祝好，
[Yang-qwq](https://github.com/Yang-qwq)

**Comment by BlueGlassBlock** [comment]
等待 lagrange-kotlin 侧完善后会进行适配，但很可能不会再追加特性了

**Comment by Yang-qwq** [comment]
> 等待 lagrange-kotlin 侧完善后会进行适配，但很可能不会再追加特性了

那请问该项目还会修复已有的/未来可能出现的问题吗？

**Comment by BlueGlassBlock** [comment]
完成适配后 bugfix 会照常提供
