### ISSUE TITLE
[Bug]当以极快的速度于QQ客服端发送任意消息时会控制台会无限打印消息

### ISSUE THREAD

**Issue by eeehhheee** [GraiaProject/Ariadne#42]
**问题**
当以极快的速度于QQ客服端发送任意消息时会控制台会无限打印消息，且永不停止

**如何复现**
在QQ客服端快速、连续打相同字符(大约1s内在QQ客服端发送4次相同消息就可以触发了)，使用的是Github该项目上面的示例代码

**预期行为**
仅显示该发送用户发送的内容

**使用环境:**

- 系统:Windows 10专业版
- MAH 版本:v2.3.3
- Ariadne 版本:graia-ariadne version: 0.4.7
- Python 版本:3.10
- 其他 Graia 库版本:graia-broadcast version: 0.14.3
- 其他 有关 库版本:mirai2.8.0RC/2.9.0-M1/2.8.2均可复现

**日志/截图**
将任何有关的日志/截图放到这里（控制台输出/MAH 输出/...)
![image](https://user-images.githubusercontent.com/64298630/144713753-1d11a231-a10c-440a-a2f2-f49bc4a07324.png)
从开始触发bug到人工介入结束程序期间QQ客服端总消息数
![image](https://user-images.githubusercontent.com/64298630/144713817-73c49817-c238-4b7e-92f1-a6f7c2f275b7.png)
Mirai控制台输出(仅节选了1s内的一小部分输出,因为余下的输出也是这样的)(诡异的是发信人和收信人是一个QQ号)
![image](https://user-images.githubusercontent.com/64298630/144713905-7dc405ec-3387-40d5-bafb-12f48b6233a2.png)
控制台输出(诡异的是发信人和收信人是一个QQ号)

**Comment by eeehhheee** [comment]
大于1s内在QQ客服端发送4次相同消息就可以触发了

**Comment by eeehhheee** [comment]
由于其他人都没办法复现这个错误，所以暂时关闭这个issue

**Comment by BlueGlassBlock** [comment]
应该是 `mirai` 本身问题： <https://github.com/mamoe/mirai/issues/1852>
