### ISSUE TITLE
[Bug] 调用 ariadne.app.Ariadne.uploadImage() 出错

### ISSUE THREAD

**Issue by SinCerely023** [GraiaProject/Ariadne#43]
**问题**
在尝试读取本地图片并上传时，调用 ariadne.app.Ariadne.uploadImage() 出错，错误信息为
```python
TypeError: Only io.IOBase, multidict and (name, file) pairs allowed, use .add_field() for passing more complex parameters, got 'sessionKey'
```
该错误信息可能与源代码中的注释相矛盾
```python
    @app_ctx_manager
    async def uploadImage(self, data: bytes, method: UploadMethod) -> "Image":
        """上传一张图片到远端服务器, 需要提供: 图片的原始数据(bytes), 图片的上传类型.
        Args:
            image_bytes (bytes): 图片的原始数据
            method (UploadMethod): 图片的上传类型
        Returns:
            Image: 生成的图片消息元素
        """
        from .message.element import Image
```
尝试使用 io.BytesIO.getvalue() 与 io.FileIO.read() 生成 bytes 均报该错误，尝试直接传入 io.BytesIO、io.FileIO、io.IOBase 仍均报该错误。
不知道是我的理解有问题还是打开方式不对，或者说bytes的格式不对……叨扰还请见谅

**如何复现**
在任意 listener 中调用 Ariadne.uploadImage() 并触发事件

**预期行为**
预期能够正常上传图片，并返回Image。如果可以的话，希望能在文档中简要提供示例

**使用环境:**

- 系统: win11 21H2
- MAH 版本: 2.3.3
- Ariadne 版本: 0.4.8
- Python 版本: 3.8.8
- 其他 Graia 库版本: 
- - Broadcast 0.14.4
- - Scheduler 0.0.4
- - Saya 0.0.13
- 其他 有关 库版本:
- - aiohttp 3.7.4.post0

**日志/截图**
MAH在报错时无其它显示
![QQ截图20211206014930](https://user-images.githubusercontent.com/62272084/144757611-3bdf1cbd-d426-43f4-ab63-2948d553507e.png)
Python运行日志
![QQ截图20211206012328](https://user-images.githubusercontent.com/62272084/144757609-7c7aff9f-74bb-45c0-99e1-a9d336ffc83e.png)
result['img'] 为 uploadImage() 的第一个输入参数，pycharm显示类型为bytes
![QQ截图20211206012118](https://user-images.githubusercontent.com/62272084/144757607-1b65506e-ea71-45a5-9a47-a07489abedcb.png)

**Comment by SinCerely023** [comment]
查了一下发现 adapter 中
```python
for k, v in data.items():
    form.add_fields(k, v)
```
修改为
```python
for k, v in data.items():
    form.add_field(k, v)
```
即可解决

**Comment by BlueGlassBlock** [comment]
已在 `0.4.8.1` 解决.
又及: 使用 `Image` 的 `path` 与 `data_bytes` 可能会更好.
