### ISSUE TITLE
[Docs] 《消息链：基础》里面有个链接挂了

### ISSUE THREAD

**Issue by ZhaoZuohong** [GraiaProject/Ariadne#45]
**需要改进的地方**

[https://graia.readthedocs.io/zh_CN/latest/basic/msg-chain/](https://graia.readthedocs.io/zh_CN/latest/basic/msg-chain/)

**需要改变的内容**

https://graiaproject.github.io/Ariadne/message/element.html -> https://graiaproject.github.io/Ariadne/ariadne/message/element.html

**额外信息**

**Comment by BlueGlassBlock** [comment]
closed in 
7e1b890
