### ISSUE TITLE
[Bug]KeybroadInterrupt退出时会出现段错误

### ISSUE THREAD

**Issue by I-love-study** [GraiaProject/Ariadne#54]
**问题**
KeybroadInterrupt退出时会出现段错误

**如何复现**
开完就Ctrl + C

**预期行为**
没段错误

**使用环境:**

- 系统:
- MAH 版本: 2.4.0
- Ariadne 版本: 0.4.9
- Python 版本: 3.9
- 其他 Graia 库版本:
- 其他 有关 库版本:

**日志/截图**
将任何有关的日志/截图放到这里（控制台输出/MAH 输出/...)
使用`faulthandler`输出的报错
<img width="792" alt="image" src="https://user-images.githubusercontent.com/39652142/145808255-87c8dd1b-53a2-45ac-94e4-d213d2828f25.png">

**Comment by BlueGlassBlock** [comment]
`CPython` 的问题.

`Ariadne` 的逻辑已经成功完成了.

你大概不用管这个.
