### ISSUE TITLE
[Bug] 接受到的消息链不含有图片

### ISSUE THREAD

**Issue by Redlnn** [GraiaProject/Ariadne#6]
**问题**
接受到的消息链不含有图片

<details>
<summary>例1</summary>
收到一条图片消息，其在Mirai的log中显示为

```
2021-11-03 14:53:44 V/Bot.xxxxxxxxx: [群名称(xxxxxxxxx)] Red_lnn(xxxxxxxxx) -> [mirai:image:{B341B788-1D4F-78C6-F77B-9709115D3D47}.jpg]
```
而bot得到的为
```
__root__=[Source(type='Source', id=1307659, time=datetime.datetime(2021, 11, 3, 6, 53, 45, tzinfo=datetime.timezone.utc))]
```
在另一机器上运行的旧版（`0.19.2`）的Graia Application得到的则是
```
__root__=(Source(id=1307659, time=datetime.datetime(2021, 11, 3, 6, 53, 45, tzinfo=datetime.timezone.utc)), Image(imageId='{B341B788-1D4F-78C6-F77B-9709115D3D47}.jpg', url='http://gchat.qpic.cn/gchatpic_new/xxxxxxxxx/726324810-2401023676-B341B7881D4F78C6F77B9709115D3D47/0?term=2', path=None, type=<ImageType.Unknown: 'Unknown'>))
```
</details>

<details>
<summary>例2</summary>
收到一条含有文本、At、图片的消息，其在Mirai的log中显示为

```
2021-11-03 15:04:37 V/Bot.xxxxxxxxx: [群名称(xxxxxxxxx)] Red_lnn(xxxxxxxxx) -> [mirai:at:xxxxxxxxx] 123456[mirai:image:{B341B788-1D4F-78C6-F77B-9709115D3D47}.jpg]789
```
而bot得到的为
```
__root__=[Source(type='Source', id=1307663, time=datetime.datetime(2021, 11, 3, 7, 4, 39, tzinfo=datetime.timezone.utc)), At(type='At', target=xxxxxxxxx, display=''), Plain(type='Plain', text=' 123456'), Plain(type='Plain', text='789')]
```
在另一机器上运行的旧版（`0.19.2`）的Graia Application得到的则是
```
__root__=(Source(id=1307663, time=datetime.datetime(2021, 11, 3, 7, 4, 39, tzinfo=datetime.timezone.utc)), At(type='At', target=xxxxxxxxx, display=''), Plain(type='Plain', text=' 123456'), Image(imageId='{B341B788-1D4F-78C6-F77B-9709115D3D47}.jpg', url='http://gchat.qpic.cn/gchatpic_new/xxxxxxxxx/726324810-3206812777-B341B7881D4F78C6F77B9709115D3D47/0?term=2', path=None, type=<ImageType.Unknown: 'Unknown'>), Plain(type='Plain', text='789'))
```
</details>

> 上面例子中包含旧版的Graia Application的信息，但由于没有升级到最新Graia Application，因此MAH版本为[`1.12.0`](https://github.com/project-mirai/mirai-api-http/releases/tag/v1.12.0)，不清楚消息链不完整是否为MAH的问题
>
> 使用 `mirai-console-loader` 启动 `mirai`，不清楚如何获得MAH的输出

**如何复现**
```python
@bcc.receiver('GroupMessage')
async def group_handler(chain: MessageChain):
   print(chain)


@bcc.receiver('FriendMessage')
async def friend_handler(chain: MessageChain):
   print(chain)
```

**预期行为**
与上面例1例2中的旧版的Graia Application获取到的消息链差不多，消息链中应含有Image对象

**使用环境:**
 - 系统: Windows 11 22000.282
 - MAH 版本: `2.3.3`
 - Ariadne 版本: `0.3.4`
 - Python 版本: `3.10.0`
 - 其他 Graia 库版本: `graia-broadcast==0.13.1`
 - 其他 有关 库版本: `pydantic==1.8.2`
 - mirai 版本: `mirai-console-2.8.0-RC` `mirai-console-terminal-2.8.0-RC` `mirai-core-all-2.8.0-RC`

**日志/截图**
将任何有关的日志/截图放到这里（控制台输出/MAH输出/...)
> 见上面的例子
- 例1消息在QQ客户端上看起来的样子
  > ![image](https://user-images.githubusercontent.com/41742767/140021873-50b9575a-8312-4918-aad8-11aee1a25d00.png)
- 例2消息在QQ客户端上看起来的样子
  > ![image](https://user-images.githubusercontent.com/41742767/140021981-fd7b8401-3490-44c8-8775-b6b5edf06411.png)

**Comment by BlueGlassBlock** [comment]
Fixed in [`0.3.6.1`](7469ae52fb4483578c9247d7f7026dcf938c325c)
