### ISSUE TITLE
[Bug] NudgeEvent

### ISSUE THREAD

**Issue by YUASDS** [GraiaProject/Ariadne#63]
**问题**
当陌生人触发戳一戳事件的时候，**会因为没有陌生人的戳一戳事件而报错**，导致程序**意外停止**
**如何复现**
陌生人在没有添加bot时通过群聊进行临时会话，直接进行戳一戳
**预期行为**
添加陌生人的触发事件

Ariadne version: 0.4.9
Broadcast version: 0.14.4
Scheduler version: Not Installed
Saya version: Not Installed

错误信息：
pydantic.error_wrappers.ValidationError: 1 validation error for NudgeEvent
context_type
  unexpected value; permitted: 'friend', 'group', None (type=value_error.const; given=stranger; permitted=('friend', 'group', None))

**Comment by YUASDS** [comment]
大概意外传入的参数是stranger

**Comment by BlueGlassBlock** [comment]
本行为未在 `mirai-api-http` 计入文档. (https://github.com/project-mirai/mirai-api-http/blob/master/docs/api/EventType.md#%E6%88%B3%E4%B8%80%E6%88%B3%E4%BA%8B%E4%BB%B6)
将在 `0.5.0` 中修复.

**Comment by YUASDS** [comment]
![image](https://user-images.githubusercontent.com/57476537/147379394-c0cfc239-d178-4c01-ae5f-bb1ecb42a605.png)

**Comment by YUASDS** [comment]
Traceback (most recent call last):

  File "c:\Users\Administrator\Desktop\dice\mirai\bot-mirai-api-http\test.py", line 72, in <module>
    loop.run_until_complete(app.lifecycle())
    │    │                  │   └ <function Ariadne.lifecycle at 0x042B9778>
    │    │                  └ <graia.ariadne.app.Ariadne object at 0x0429EF70>
    │    └ <function BaseEventLoop.run_until_complete at 0x0389F7C0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39-32\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
    │    └ <function ProactorEventLoop.run_forever at 0x039374F0>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39-32\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39-32\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x038B1538>
    └ <ProactorEventLoop running=True closed=False debug=False>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39-32\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x03862BF8>
    └ <Handle <TaskWakeupMethWrapper object at 0x04B92928>(<Future finished result=None>)>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39-32\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskWakeupMethWrapper object at 0x04B92928>(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskWakeupMethWrapper object at 0x04B92928>(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskWakeupMethWrapper object at 0x04B92928>(<Future finished result=None>)>

> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39-32\lib\site-packages\graia\broadcast\__init__.py", line 166, in Executor
    result = await run_always_await_safely(target_callable, **parameter_compile_result)
                   │                       │                  └ {'app': <graia.ariadne.app.Ariadne object at 0x0429EF70>, 'event': NudgeEvent(type='NudgeEvent', supplicant=819793723, target...
                   │                       └ <function getup at 0x042B9A90>
                   └ <function run_always_await_safely at 0x03979A48>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39-32\lib\site-packages\graia\broadcast\utilles.py", line 23, in run_always_await_safely
    return await callable(*args, **kwargs)
                 │         │       └ {'app': <graia.ariadne.app.Ariadne object at 0x0429EF70>, 'event': NudgeEvent(type='NudgeEvent', supplicant=819793723, target...
                 │         └ ()
                 └ <function getup at 0x042B9A90>

  File "c:\Users\Administrator\Desktop\dice\mirai\bot-mirai-api-http\test.py", line 43, in getup
    await app.sendFriendMessage(
          │   └ <function MessageMixin.sendFriendMessage at 0x042AE070>
          └ <graia.ariadne.app.Ariadne object at 0x0429EF70>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39-32\lib\site-packages\graia\ariadne\util\__init__.py", line 190, in wrapper
    return await func(self, *args, **kwargs)
                 │    │      │       └ {}
                 │    │      └ (None, MessageChain([Plain(text='别戳我，好痒'), Plain(text='id'), Plain(text='kind'), Image(base64='/9j/4AAQSkZJRgABAQEASABIAAD/2w...
                 │    └ <graia.ariadne.app.Ariadne object at 0x0429EF70>
                 └ <function MessageMixin.sendFriendMessage at 0x042AE028>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39-32\lib\site-packages\graia\ariadne\app.py", line 111, in sendFriendMessage
    result = await self.adapter.call_api(
                   │    │       └ <function HttpAdapter.call_api at 0x0429FB20>
                   │    └ <graia.ariadne.adapter.CombinedAdapter object at 0x0429EFA0>
                   └ <graia.ariadne.app.Ariadne object at 0x0429EF70>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39-32\lib\site-packages\graia\ariadne\adapter.py", line 66, in wrapped_network_action_callable
    result = await network_action_callable(self, *args, **kwargs)
                   │                       │      │       └ {}
                   │                       │      └ ('sendFriendMessage', <CallMethod.POST: 'POST'>, {'sessionKey': 'xTeoLhpI', 'target': None, 'messageChain': [{'type': 'Plain'...
                   │                       └ <graia.ariadne.adapter.CombinedAdapter object at 0x0429EFA0>
                   └ <function HttpAdapter.call_api at 0x0429FA90>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39-32\lib\site-packages\graia\ariadne\adapter.py", line 273, in call_api
    validate_response(resp)
    │                 └ {'code': 5, 'msg': '指定对象不存在'}
    └ <function validate_response at 0x03AE7CD0>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39-32\lib\site-packages\graia\ariadne\util\__init__.py", line 84, in validate_response
    raise exc_cls(exc_cls.__doc__)
          │       │       └ '对象位置未知, 不存在或不可及.'
          │       └ <class 'graia.ariadne.exception.UnknownTarget'>
          └ <class 'graia.ariadne.exception.UnknownTarget'>

graia.ariadne.exception.UnknownTarget: 对象位置未知, 不存在或不可及.

**Comment by YUASDS** [comment]
**相关代码**
        if event.context_type == "group":
            await app.sendGroupMessage(event.group_id,
                                       MessageChain.create(random.choice(f)))
        else:
            await app.sendFriendMessage(
                event.friend_id,
                MessageChain.create("别戳我，好痒", event.origin_subject_info,
                                    Image(path="D:\\img\\preview.jpg")))
**版本**：
Ariadne version: 0.5.0b1
Broadcast version: 0.14.5

**Comment by YUASDS** [comment]
**好友**
graia.ariadne.adapter:build_event:518 - type='NudgeEvent' supplicant=178 target=9596 msg_action='戳了戳' msg_suffix='' origin_subject_info={'id': 178, 'kind': 'Friend'} friend_id=None group_id=None context_type='friend'

graia.ariadne.exception.UnknownTarget: 对象位置未知, 不存在或不可及.

**群**
graia.ariadne.adapter:build_event:518 - type='NudgeEvent' supplicant=178 target=9596 msg_action='戳了戳' msg_suffix='' origin_subject_info={'id': 871, 'kind': 'Group'} friend_id=None group_id=None context_type='group'

**陌生人**
**在群内添加好友后，立刻进行戳一戳的情况**
graia.ariadne.adapter:build_event:518 - type='NudgeEvent' supplicant=178 target=9596 msg_action='戳了戳' msg_suffix='' origin_subject_info={'id': 819, 'kind': 'Stranger'} friend_id=None group_id=None context_type='stranger'
