### ISSUE TITLE
[Bug]发送群消息时若包含At元素则会出现异常

### ISSUE THREAD

**Issue by eeehhheee** [GraiaProject/Ariadne#7]
**问题**
发送群消息时若包含At元素则会出现异常，经调试应该是生成data时某些Graia的元素没有删除导致对MAH API的调用失败

**如何复现**
```python
 @bcc.receiver(GroupMessage)
    async def reply(app: Ariadne, chain: MessageChain, group: Group, member: Member):
        if chain.asDisplay() == "Hi!":
            await app.sendGroupMessage(group, MessageChain.create([At(member.id), Plain("Hello World!")]))
```

**预期行为**
发送的消息包含At元素

**使用环境:**
 - 系统: Windows 10 专业版
 - MAH 版本: v2.3.3
 - Ariadne 版本:0.3.3.2
 - Python 版本:3.10
 - 其他 Graia 库版本:graia-broadcast 0.13.1 graia-saya 0.0.13
 - 其他 有关 库版本:默认版本

**日志/截图**
![image](https://user-images.githubusercontent.com/64298630/140237570-7ae5d8eb-1674-45ed-bbbd-12a8e6ffa37d.png)
![image](https://user-images.githubusercontent.com/64298630/140237390-0602f4bf-b97a-4d00-af2d-99c729348be9.png)

**Comment by BlueGlassBlock** [comment]
应该是 `model.dict()` 的锅......

正在修复.
