### ISSUE TITLE
[Feature] 增加对于其他操作和事件的 log

### ISSUE THREAD

**Issue by I-love-study** [GraiaProject/Ariadne#73]
**使用场景**
现阶段只有**接收消息**和**发送消息**会有相关 log 的提示
而其他方法（如禁言群员，退出群聊）和事件（比如xxx被禁言了）还有却没有 任何 log 提示
假设加上相关 log，会不会使这个日志变得更加像日志呢？

**你想要的解决方案**
将所有**非获取的方法**（即不是以 `get` 开头的方法）和其他 `mirai` 事件加上 log 记录

**是否已有相关实现**

**其他内容**
具体怎么做（如将 log 分类什么的）可能还有待商榷

**Comment by BlueGlassBlock** [comment]
这个 mirai-console 已经做了, 在 Ariadne 端做需要强制启用 `bypass_listener` 特性.
我可能会通过 audit hook 的方式实现这个: 给所有 api 操作加上 audit hook.
