### ISSUE TITLE
[Bug]使用MultimediaMixin.uploadImage上传图像并获得Image对象时出现异常

### ISSUE THREAD

**Issue by eeehhheee** [GraiaProject/Ariadne#8]
**问题**
使用MultimediaMixin.uploadImage上传图像并获得Image对象时出现异常，经调试发现call_api(Http那个)函数中
```
for k, v in data:
                form.add_fields(k, v)
```
语句报错,将该语句改为
```
for k, v in data.items():
        form.add_field(k, v)
```

后异常消失，行为恢复正常

**如何复现**
使用MultimediaMixin.uploadImage上传任意图像

**预期行为**
获得Image对象并发出

**使用环境:**
 - 系统: Windows 10 专业版
 - MAH 版本: v2.3.3
 - Ariadne 版本:0.3.7
 - Python 版本:3.10
 - 其他 Graia 库版本:默认版本
 - 其他 有关 库版本: 默认版本

**日志/截图**
![image](https://user-images.githubusercontent.com/64298630/140630178-dd141963-2606-4e6c-87aa-ddee842dd9d7.png)

**Comment by BlueGlassBlock** [comment]
因为 app.upload* 在 Ariadne 里 并不是很有必要 >_> 我现在修掉
